//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SсhoolPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int id { get; set; }
        public int idLearning { get; set; }
        public System.DateTime Date { get; set; }
        public string Issued { get; set; }
    
        public virtual Learning Learning { get; set; }
    }
}
