//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SсhoolPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTopic
    {
        public int id { get; set; }
        public int idCourse { get; set; }
        public int idTopic { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Topics Topics { get; set; }
    }
}
