//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SсhoolPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public int id { get; set; }
        public int idTimetable { get; set; }
        public int idSubject { get; set; }
        public int idTeacher { get; set; }
        public int Number { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual Timetable Timetable { get; set; }
    }
}
